# Generated by Django 5.0.4 on 2024-04-27 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_comments_deals_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Watchlist',
        ),
        migrations.AddField(
            model_name='comments',
            name='Prouct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='auctions.products'),
        ),
        migrations.AddField(
            model_name='products',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
                ('Product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='auctions.products')),
            ],
        ),
    ]
