# Generated by Django 5.0.4 on 2024-04-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_products_watchlist_comments_prouct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='image/Project2/'),
        ),
    ]
