# Generated by Django 5.0.4 on 2024-04-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_products_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Final_Price',
            field=models.FloatField(default=0),
        ),
    ]
