# Generated by Django 5.0.4 on 2024-04-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_products_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Title',
            field=models.CharField(max_length=64),
        ),
    ]
