# Generated by Django 4.2.11 on 2024-05-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_products_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
