# Generated by Django 4.2.11 on 2024-05-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Prouct',
            new_name='Product',
        ),
    ]
